// Auto-generated from the Google Sheets "הגמחים של ישראל".
// One-time import. Do not edit by hand — regenerate from the sheet if needed.

import type { Gemach } from './gemachData';

export interface StaticGemach extends Gemach {
    contact?: string;
    link?: string;
    notes?: string;
}

export const staticGemachim: StaticGemach[] = [
    {
        id: "1000",
        name: "גמ\"ח ברית מילה - כרית",
        category: "wedding",
        city: "בית שמש",
        neighborhood: "נחל רפאים 40, דירה 6",
        phone: "0586827276",
        description: "בגד לברית, תפילות, מדריך לברית,  וטיפול אחרי הברית",
        link: "https://www.shemesh.co.il/directory/gemachim/location-gm-h-vryt-mylh-khryt/details",
        tags: ["בגד לברית","תפילות","מדריך לברית","וטיפול אחרי הברית","בית שמש"],
    },
    {
        id: "1001",
        name: "אביטן - גמ\"ח כרית ברית מילה",
        category: "wedding",
        city: "בית שמש",
        neighborhood: "מרים הנביאה 4, דירה 9",
        phone: "0533113889",
        description: "כרית לברית מילה",
        link: "https://www.shemesh.co.il/directory/gemachim/location-vytn-gm-h-khryt-vryt-mylh-31/details",
        tags: ["כרית לברית מילה","בית שמש"],
    },
    {
        id: "1002",
        name: "ברית אברהם - גמ\"ח כרית לברית מילה",
        category: "wedding",
        city: "בית שמש",
        neighborhood: "נהר הירדן 42, דירה 3",
        phone: "0548458473",
        description: "ערכה מלאה לברית",
        link: "https://www.shemesh.co.il/directory/gemachim/location-vryt-vrhm-gm-h-khryt-lvryt-mylh-73/details",
        tags: ["ערכה מלאה לברית","בית שמש"],
    },
    {
        id: "1003",
        name: "ג'סי כהן (עמותה)",
        category: "other",
        city: "חולון",
        phone: "0509111191",
        description: "אורחות חג, מסיבות לאוטיסטים",
        contact: "יונתן",
        link: "https://www.facebook.com/Jessy.cohen.net?locale=he_IL",
        tags: ["אורחות חג","מסיבות לאוטיסטים","חולון"],
    },
    {
        id: "1004",
        name: "תפילה לכלה",
        category: "wedding",
        city: "אלעד",
        neighborhood: "שמעיה 12 א",
        phone: "03-9095052",
        description: "שערים, מצנח וכו'",
        tags: ["שערים","מצנח וכו'","אלעד"],
    },
    {
        id: "1005",
        name: "גמח במחיר סמלי",
        category: "wedding",
        city: "אשדוד",
        phone: "058-3221898",
        description: "מצנח וסלסלה",
        tags: ["מצנח וסלסלה","אשדוד"],
    },
    {
        id: "1006",
        name: "אביזרי כלה",
        category: "wedding",
        city: "בני ברק",
        phone: "03-6197826",
        description: "לכלה בצבע לבן וכסף, מצנח, גיטרה, מקבל בלונים, קשתות, מטריה, סלסלה",
        tags: ["לכלה בצבע לבן וכסף","מצנח","גיטרה","מקבל בלונים","בני ברק"],
    },
    {
        id: "1007",
        name: "כהן",
        category: "wedding",
        city: "בני ברק",
        phone: "03-6180869",
        description: "תפילה לכלה, אביזרים לריקודים",
        tags: ["תפילה לכלה","אביזרים לריקודים","בני ברק"],
    },
    {
        id: "1008",
        name: "דהן",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "בן יעקב 30",
        phone: "03-5747742",
        description: "אביזרים לריקודים בתיאום",
        tags: ["אביזרים לריקודים בתיאום","בני ברק"],
    },
    {
        id: "1009",
        name: "הנדלסמן",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "השומר 61",
        phone: "03-5700412",
        description: "קוב תפילות לכלה, הכנה לנישואין וליום החופה",
        tags: ["קוב תפילות לכלה","הכנה לנישואין וליום החופה","בני ברק"],
    },
    {
        id: "1010",
        name: "א.כהן",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "גני גד 3",
        phone: "03-6180869",
        description: "אביזרים יוקרתיים וחדישים, כולל מצנח ענק",
        tags: ["אביזרים יוקרתיים וחדישים","כולל מצנח ענק","בני ברק"],
    },
    {
        id: "1011",
        name: "בקשי",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "רבי מאיר 3",
        phone: "03-6182307",
        description: "עששיות לחופה ועוד",
        tags: ["עששיות לחופה ועוד","בני ברק"],
    },
    {
        id: "1012",
        name: "שמחת נעמי",
        category: "furniture",
        city: "בני ברק",
        neighborhood: "אברהם בן דוד 18",
        phone: "03-6768403",
        description: "אגרטלים לשולחן",
        tags: ["אגרטלים לשולחן","בני ברק"],
    },
    {
        id: "1013",
        name: "גולדברג",
        category: "wedding",
        city: "בני ברק",
        phone: "03-6195926",
        description: "אביזרים לכלה, בתיאום",
        tags: ["אביזרים לכלה","בתיאום","בני ברק"],
    },
    {
        id: "1014",
        name: "גמ\"ח סלסלות לבר, מרכז שולחן בצורות יפות",
        category: "wedding",
        city: "בני ברק",
        phone: "03-5702492",
        description: "גמ\"ח סלסלות לבר, מרכז שולחן בצורות יפות",
        tags: ["גמ\"ח סלסלות לבר","מרכז שולחן בצורות יפות","בני ברק"],
    },
    {
        id: "1015",
        name: "שמחת חיה לע\"נ חיה רייזל רייך",
        category: "wedding",
        city: "בני ברק",
        phone: "03-6194373",
        description: "אביזרים חדישים לכלה",
        tags: ["אביזרים חדישים לכלה","בני ברק"],
    },
    {
        id: "1016",
        name: "זרגרי חסדי חנה",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "יונה הנביא 9",
        phone: "03-6194771",
        description: "אביזרי כלה, בתיאום",
        tags: ["אביזרי כלה","בתיאום","בני ברק"],
    },
    {
        id: "1017",
        name: "כהן",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "כהנמן 77",
        phone: "03-5709678",
        description: "תפילה לכלה, בתיאום",
        tags: ["תפילה לכלה","בתיאום","בני ברק"],
    },
    {
        id: "1018",
        name: "יוסף",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "לופיאן 7",
        phone: "02-5879927",
        description: "אביזרים לריקודים",
        tags: ["אביזרים לריקודים","ירושלים"],
    },
    {
        id: "1019",
        name: "שמח תשמח",
        category: "wedding",
        city: "ירושלים",
        phone: "02-5820967",
        description: "אביזרים לריקודים גוש שמונים",
        tags: ["אביזרים לריקודים גוש שמונים","ירושלים"],
    },
    {
        id: "1020",
        name: "עזרת מרים",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "עזרת תורה 36",
        phone: "02-5386461",
        description: "תפילה לכלה אביזרים לריקודים",
        tags: ["תפילה לכלה אביזרים לריקודים","ירושלים"],
    },
    {
        id: "1021",
        name: "דורי",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "צפניה 8",
        phone: "02-5378384",
        description: "אביזרים לריקודים",
        tags: ["אביזרים לריקודים","ירושלים"],
    },
    {
        id: "1022",
        name: "פרחי מרים",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "עלי הכהן 15 בתיאום",
        phone: "02-5388069",
        description: "סלסלות לכלה ולשושבינות, עמודים, עמודי פרחים לכסא כלה",
        tags: ["סלסלות לכלה ולשושבינות","עמודים","עמודי פרחים לכסא כלה","ירושלים"],
    },
    {
        id: "1023",
        name: "יוסף",
        category: "other",
        city: "ירושלים",
        neighborhood: "לופיאן 7",
        phone: "02-5879927",
        description: "תחתיות",
        tags: ["תחתיות","ירושלים"],
    },
    {
        id: "1024",
        name: "גמ\"ח כתרים לכלות",
        category: "wedding",
        city: "ירושלים",
        phone: "02-5386239",
        description: "גמ\"ח כתרים לכלות",
        tags: ["גמ\"ח כתרים לכלות","ירושלים"],
    },
    {
        id: "1025",
        name: "אליאס",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "פולנסקי 18",
        phone: "02-5322040",
        description: "סלסלות, מטריה, קשתות, דרבוקות, מצנח, מעודדות,ביצים, נצנץ",
        tags: ["סלסלות","מטריה","קשתות","דרבוקות","ירושלים"],
    },
    {
        id: "1026",
        name: "וינברג",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "צפניה 11",
        phone: "02-5822149",
        description: "קשתות",
        tags: ["קשתות","ירושלים"],
    },
    {
        id: "1027",
        name: "זכרון בטי",
        category: "furniture",
        city: "ירושלים",
        phone: "02-5862837",
        description: "מרכזי שולחן",
        tags: ["מרכזי שולחן","ירושלים"],
    },
    {
        id: "1028",
        name: "חדוות רבקה",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "ארץ חפץ 116/29",
        phone: "02-5827618",
        description: "מצנח, מעודדות, סלסלה, קשתות",
        tags: ["מצנח","מעודדות","סלסלה","קשתות","ירושלים"],
    },
    {
        id: "1029",
        name: "חדוות רבקה",
        category: "furniture",
        city: "ירושלים",
        neighborhood: "ארץ חפץ 116/29",
        phone: "02-5827618",
        description: "כסאות ושולחנות",
        tags: ["כסאות ושולחנות","ירושלים"],
    },
    {
        id: "1030",
        name: "פיונטיקה",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "קלונימוס 18",
        phone: "02-5711281",
        description: "אביזרים לריקודים",
        tags: ["אביזרים לריקודים","ירושלים"],
    },
    {
        id: "1031",
        name: "שמחת חנה",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "131/10",
        phone: "02-5400782",
        description: "אביזרים לריקודים",
        tags: ["אביזרים לריקודים","ירושלים"],
    },
    {
        id: "1032",
        name: "שמחת כלה",
        category: "wedding",
        city: "מודיעין עילית",
        phone: "08-9298110",
        description: "מצנח, סלסלה, קשתות, מעודדות ועוד",
        tags: ["מצנח","סלסלה","קשתות","מעודדות ועוד","מודיעין עילית"],
    },
    {
        id: "1033",
        name: "שנלזון",
        category: "wedding",
        city: "מודיעין עילית",
        phone: "08-9744704",
        description: "תפילה לכלה, תופים, דרבוקות, מעודדות, קשקשנים",
        tags: ["תפילה לכלה","תופים","דרבוקות","מעודדות","מודיעין עילית"],
    },
    {
        id: "1034",
        name: "בצלאל",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "נועם אלימלך 11 ב'",
        phone: "03-5700631",
        description: "הינומה ונעליים",
        tags: ["הינומה ונעליים","בני ברק"],
    },
    {
        id: "1035",
        name: "גוטליב \"ויעל אליהו\"",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "קהילות יעקב 17",
        phone: "03-03-673017",
        description: "גוטליב \"ויעל אליהו\"",
        tags: ["גוטליב \"ויעל אליהו\"","בני ברק"],
    },
    {
        id: "1036",
        name: "רוטשטיין \"שירת אדר\"ת\"",
        category: "wedding",
        city: "בני ברק",
        neighborhood: "רבי יוסי 6",
        phone: "03-6180962",
        description: "רוטשטיין \"שירת אדר\"ת\"",
        tags: ["רוטשטיין \"שירת אדר\"ת\"","בני ברק"],
    },
    {
        id: "1037",
        name: "קו רהיטים ומוצרים שונים למסירה",
        category: "other",
        city: "",
        phone: "073-3640811",
        description: "קו רהיטים ומוצרים שונים למסירה",
        tags: ["קו רהיטים ומוצרים שונים למסירה"],
    },
    {
        id: "1038",
        name: "גמח הדקה ה-90",
        category: "furniture",
        city: "",
        phone: "052-9251547",
        description: "מיחמים, פלטות לשבת, שולחנות פלסטיק ועוד",
        tags: ["מיחמים","פלטות לשבת","שולחנות פלסטיק ועוד"],
    },
    {
        id: "1039",
        name: "גמח השאלת תפילין רש\"י ור\"ת גם לאיטר יד",
        category: "judaism",
        city: "",
        phone: "053-3171313",
        description: "גמח השאלת תפילין רש\"י ור\"ת גם לאיטר יד",
        tags: ["גמח השאלת תפילין רש\"י ור\"ת גם לאיטר יד"],
    },
    {
        id: "1040",
        name: "גמח ספרונים לברית יצחק וחנוכת בית",
        category: "judaism",
        city: "",
        phone: "054-7530076",
        description: "לפנות לשי",
        tags: ["לפנות לשי"],
    },
    {
        id: "1041",
        name: "חלוקת ארוחות חמות למשפחות נזקקות",
        category: "food",
        city: "נתיבות",
        phone: "053-5264738",
        description: "שלמה יחיאל",
        tags: ["שלמה יחיאל","נתיבות"],
    },
    {
        id: "1042",
        name: "אלה תמרין ציוד לחיילים פצועים",
        category: "wedding",
        city: "",
        phone: "054-5749856",
        description: "פצועי גפיים הלבשה תחתונה מיוחדת לחיילים",
        tags: ["פצועי גפיים הלבשה תחתונה מיוחדת לחיילים"],
    },
    {
        id: "1043",
        name: "אליענה פריאל עיצובים",
        category: "wedding",
        city: "גדרה",
        neighborhood: "אבא אחימאיר 10",
        phone: "052-5285275",
        description: "אופנה לנשים/כלות",
        contact: "אליענה",
        notes: "בתיאום בלבד",
        tags: ["אופנה לנשים/כלות","גדרה"],
    },
    {
        id: "1044",
        name: "אורי גמח כלות",
        category: "wedding",
        city: "אלעד",
        phone: "052-8865665",
        description: "שמלות איפור וסירוק",
        tags: ["שמלות איפור וסירוק","אלעד"],
    },
    {
        id: "1045",
        name: "ליאנה גמח",
        category: "wedding",
        city: "שמלות כלה",
        neighborhood: "אור יהודה",
        phone: "054-3036065",
        description: "שמלות כלה",
        tags: ["שמלות כלה"],
    },
    {
        id: "1046",
        name: "תקליטן לחתונות",
        category: "wedding",
        city: "",
        phone: "054-8849344",
        description: "מוזיקה לחתונות",
        tags: ["מוזיקה לחתונות"],
    },
    {
        id: "1047",
        name: "בתיה",
        category: "wedding",
        city: "",
        phone: "052-3003153",
        description: "גמח שמלות",
        tags: ["גמח שמלות"],
    },
    {
        id: "1048",
        name: "אודליה",
        category: "food",
        city: "",
        phone: "050-7809882",
        description: "גמח מזון וריהוט",
        tags: ["גמח מזון וריהוט"],
    },
    {
        id: "1049",
        name: "חיה רוזן",
        category: "wedding",
        city: "",
        neighborhood: "באר שבע",
        phone: "054-6303085",
        description: "גמח כלות",
        tags: ["גמח כלות"],
    },
    {
        id: "1050",
        name: "קארין",
        category: "wedding",
        city: "רמלה",
        phone: "050-9254946",
        description: "גמח לכלות",
        tags: ["גמח לכלות","רמלה"],
    },
    {
        id: "1051",
        name: "אלינור",
        category: "wedding",
        city: "",
        neighborhood: "דימונה",
        phone: "058-6276566",
        description: "סלון לכלות",
        tags: ["סלון לכלות"],
    },
    {
        id: "1052",
        name: "שמלות כלה",
        category: "wedding",
        city: "",
        phone: "052-3121512",
        description: "שמלות כלה",
        tags: ["שמלות כלה"],
    },
    {
        id: "1053",
        name: "עדנה",
        category: "wedding",
        city: "",
        phone: "052-3121512",
        description: "גמח נדוניה",
        tags: ["גמח נדוניה"],
    },
    {
        id: "1054",
        name: "דבי",
        category: "wedding",
        city: "",
        neighborhood: "רעננה",
        phone: "050-2570570",
        description: "גמח שמלות",
        tags: ["גמח שמלות"],
    },
    {
        id: "1055",
        name: "ורד גליק",
        category: "wedding",
        city: "רמת גן",
        phone: "050-7360770",
        description: "גמח כלות",
        notes: "ע\"ש אפרת כהן ז\"ל",
        tags: ["גמח כלות","רמת גן"],
    },
    {
        id: "1056",
        name: "סמדר זאבי",
        category: "wedding",
        city: "פתח תקווה",
        phone: "050-9908775",
        description: "אביזרים לכלות",
        tags: ["אביזרים לכלות","פתח תקווה"],
    },
    {
        id: "1057",
        name: "אחותי כלה עמותה",
        category: "wedding",
        city: "",
        phone: "052-5758284",
        description: "אביזרים לכלה",
        contact: "054-4563544",
        notes: "ע\"ש דנה גליק ז\"ל",
        tags: ["אביזרים לכלה"],
    },
    {
        id: "1058",
        name: "לפני חתונה",
        category: "wedding",
        city: "כולל הפרשת חלה",
        phone: "054-5571022",
        description: "חינה וה.חלה ערב מקוה",
        notes: "כולל הגברה",
        tags: ["חינה וה.חלה ערב מקוה","כולל הפרשת חלה"],
    },
    {
        id: "1059",
        name: "לכלה חינם",
        category: "wedding",
        city: "כל האביזרים והציוד",
        phone: "052-3339002",
        description: "כל האביזרים והציוד",
        tags: ["כל האביזרים והציוד"],
    },
    {
        id: "1060",
        name: "בר/בת מצווה ליתומים",
        category: "wedding",
        city: "כל הציוד ואולם, תפילין ועוד",
        phone: "052-6087084",
        description: "כל הציוד ואולם, תפילין ועוד",
        tags: ["כל הציוד ואולם","תפילין ועוד","כל הציוד ואולם, תפילין ועוד"],
    },
    {
        id: "1061",
        name: "משמחי כלה",
        category: "wedding",
        city: "",
        phone: "050-3332729",
        description: "כל האביזרים והציוד",
        tags: ["כל האביזרים והציוד"],
    },
    {
        id: "1062",
        name: "כסא כלה",
        category: "wedding",
        city: "בני ברק",
        phone: "054-8405882",
        description: "ברכת כלה, זרים במחיר סמלי",
        contact: "ליאורה",
        notes: "כסא ב200 שח",
        tags: ["ברכת כלה","זרים במחיר סמלי","בני ברק"],
    },
    {
        id: "1063",
        name: "איפור לכלות אמהות ומלוות",
        category: "wedding",
        city: "כל הארץ",
        phone: "054-7771487",
        description: "כל הארץ",
        tags: ["כל הארץ"],
    },
    {
        id: "1064",
        name: "איפור ועיצוב שיער",
        category: "wedding",
        city: "",
        phone: "050-4147386",
        description: "איפור ועיצוב שיער",
        notes: "מחיר עלות",
        tags: ["איפור ועיצוב שיער"],
    },
    {
        id: "1065",
        name: "תקליטן/די.ג'יי",
        category: "wedding",
        city: "",
        phone: "050-4147386",
        description: "תקליטן/די.ג'יי",
        notes: "חרדי ולחוזרים בתשובה",
        tags: ["תקליטן/די.ג'יי"],
    },
    {
        id: "1066",
        name: "כלות ונשים",
        category: "wedding",
        city: "איזור י-ם",
        neighborhood: "מגיעה אליכן",
        phone: "054-6348117",
        description: "כלות ונשים",
        tags: ["כלות ונשים","איזור י-ם"],
    },
    {
        id: "1067",
        name: "הדרכת כלות",
        category: "wedding",
        city: "אשדוד",
        phone: "050-2904440",
        description: "הדרכת כלות",
        notes: "מחיר סמלי",
        tags: ["הדרכת כלות","אשדוד"],
    },
    {
        id: "1068",
        name: "הדרכת כלות דליה",
        category: "wedding",
        city: "פתח תקווה",
        phone: "050-9091212",
        description: "הדרכת כלות דליה",
        notes: "חינם",
        tags: ["הדרכת כלות דליה","פתח תקווה"],
    },
    {
        id: "1069",
        name: "הדרכת כלות נעמה",
        category: "wedding",
        city: "",
        phone: "054-5571022",
        description: "הדרכת כלות נעמה",
        tags: ["הדרכת כלות נעמה"],
    },
    {
        id: "1070",
        name: "תקליטן/דיג'יי/גיטרה",
        category: "wedding",
        city: "בית שמש",
        neighborhood: "והאיזור",
        phone: "053-5220623",
        description: "ליתומים ואלמנות",
        contact: "שלום אליהו דדון",
        notes: "מגזר דתי חרדי",
        tags: ["ליתומים ואלמנות","בית שמש"],
    },
    {
        id: "1071",
        name: "תפילין חדשים לחיילים",
        category: "judaism",
        city: "",
        phone: "528702794",
        description: "לחיילים",
        contact: "ווטסאפ בלבד",
        tags: ["לחיילים"],
    },
    {
        id: "1072",
        name: "חסד לדרכם",
        category: "food",
        city: "קריות",
        phone: "545510770",
        description: "גמח אוכל",
        contact: "מאור קורקוס",
        tags: ["גמח אוכל","קריות"],
    },
    {
        id: "1073",
        name: "עזרה כללית בכל נושא",
        category: "initiatives",
        city: "כל הארץ",
        phone: "052-7611122",
        description: "עזרה כללית בכל נושא",
        contact: "מתאם חברותות",
        notes: "מפנה לאנשי מקצוע רלוונטיים",
        tags: ["עזרה כללית בכל נושא","כל הארץ"],
    },
    {
        id: "1074",
        name: "תכשיטים לבנות מצווה",
        category: "wedding",
        city: "מודיעין",
        phone: "050-2125305",
        description: "תכשיטים",
        contact: "אורית מצוב",
        link: "https://docs.google.com/spreadsheets/d/1NVyqHp8VImlBEQ3j7-2MYLdQ9s1nqaplgrnSn2nxrBE/edit?usp=sharing",
        notes: "גמ\"ח השאלה",
        tags: ["תכשיטים","מודיעין"],
    },
    {
        id: "1075",
        name: "תמיכה ליולדות ועזרה בהנקה",
        category: "medical",
        city: "פתח תקווה",
        phone: "052-6884797",
        description: "יולדות",
        contact: "שיינדל אדלר",
        notes: "רק בפ\"ת",
        tags: ["יולדות","פתח תקווה"],
    },
    {
        id: "1076",
        name: "בתים פתוחים לחתונות",
        category: "wedding",
        city: "",
        description: "בתים פתוחים לחתונות",
        link: "https://docs.google.com/spreadsheets/d/1NVyqHp8VImlBEQ3j7-2MYLdQ9s1nqaplgrnSn2nxrBE/edit?usp=sharing",
        tags: ["בתים פתוחים לחתונות"],
    },
    {
        id: "1077",
        name: "מוזיקה לאירועים",
        category: "wedding",
        city: "ירושלים והסביבה",
        phone: "058-365-9951",
        description: "מוזיקה לאירועים",
        contact: "אלעזר חזן",
        notes: "מבקש עלות נסיעות",
        tags: ["מוזיקה לאירועים","ירושלים והסביבה"],
    },
    {
        id: "1078",
        name: "בואו לקחת למסירה בחינם",
        category: "other",
        city: "הכל",
        description: "הכל",
        contact: "הלל",
        link: "https://www.facebook.com/groups/620116144831121/?ref=share&mibextid=NSMWBT",
        tags: ["הכל"],
    },
    {
        id: "1079",
        name: "גמח משפחת המגיד חינם!",
        category: "other",
        city: "איזור ירושלים",
        phone: "052-8662222",
        description: "ציוד",
        contact: "02-6524003",
        tags: ["ציוד","איזור ירושלים"],
    },
    {
        id: "1080",
        name: "סולמות, עגלות משא, תיקי נסיעה, טלפונים, פלאפונים, מצלמות ידאו, כלי עבודה חשמלי וידני, שואבי אבק, מאווררים, מכשיר לפתיחת סתימות (נחש), מזרונים, חבלים - רטשט, מיחמי מים, פלטות שבת, ציוד הגברה, פרוז'קטורים, כסאות רכב לתינוק, בוסטרים, מכשירי וויז, שולחנות, כסאות, מגאפונים לתערוכות, מקרנים, מסכי מקרן, כבל חשמל מאריך!!! הכל חינם!!!",
        category: "baby",
        city: "",
        description: "סולמות, עגלות משא, תיקי נסיעה, טלפונים, פלאפונים, מצלמות ידאו, כלי עבודה חשמלי וידני, שואבי אבק, מאווררים, מכשיר לפתיחת סתימות (נחש), מזרונים, חבלים - רטשט, מיחמי מים, פלטות שבת, ציוד הגברה, פרוז'קטורים, כסאות רכב לתינוק, בוסטרים, מכשירי וויז, שולחנות, כסאות, מגאפונים לתערוכות, מקרנים, מסכי מקרן, כבל חשמל מאריך!!! הכל חינם!!!",
        tags: ["סולמות","עגלות משא","תיקי נסיעה","טלפונים"],
    },
    {
        id: "1081",
        name: "הכנסת כלה חיה רוזן",
        category: "wedding",
        city: "באר שבע",
        phone: "054-6303085",
        description: "מוצרים לכלה",
        contact: "חיה רוזן",
        notes: "ווטסאפ",
        tags: ["מוצרים לכלה","באר שבע"],
    },
    {
        id: "1082",
        name: "קרטונים חינם",
        category: "tools",
        city: "ירושלים",
        neighborhood: "תלפיות",
        phone: "050-2799803",
        description: "קרטונים",
        contact: "דניאל",
        notes: "5 שח פקדון לקרטון המוחזר עם החזרת הקרטונים",
        tags: ["קרטונים","ירושלים"],
    },
    {
        id: "1083",
        name: "לב חבד חסד ומרפא פ\"ת",
        category: "medical",
        city: "פתח תקווה",
        neighborhood: "בלינסון והשרון",
        phone: "050",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "אפי סגל",
        link: "https://levchabad.org.il/branche/%d7%a4%d7%aa%d7%97-%d7%aa%d7%a7%d7%95%d7%95%d7%94/",
        notes: "יש עוד עשרות אנשים",
        tags: ["סיוע לחולים ומשפחותיהם","פתח תקווה"],
    },
    {
        id: "1084",
        name: "לב חבד חסד ומרפא אסף הרופא",
        category: "medical",
        city: "",
        neighborhood: "אסף הרופא",
        phone: "053-629-0363",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "מענדי ויהודית בקרמן",
        link: "https://levchabad.org.il/branche/%d7%a9%d7%9e%d7%99%d7%a8-%d7%90%d7%a1%d7%a3-%d7%94%d7%a8%d7%95%d7%a4%d7%90/",
        tags: ["סיוע לחולים ומשפחותיהם"],
    },
    {
        id: "1085",
        name: "לב חבד חסד ומרפא אשדוד",
        category: "medical",
        city: "אשדוד",
        phone: "052-676-5973",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "צבי ופנינה גודמן",
        link: "https://levchabad.org.il/branche/%d7%90%d7%a1%d7%95%d7%aa%d7%90_%d7%90%d7%a9%d7%93%d7%95%d7%93/",
        tags: ["סיוע לחולים ומשפחותיהם","אשדוד"],
    },
    {
        id: "1086",
        name: "לב חבד חסד ומרפא סורוקה",
        category: "medical",
        city: "באר שבע",
        neighborhood: "סורוקה",
        phone: "052-770-3180",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "יוסי ושושי ליצמן",
        link: "https://levchabad.org.il/branche/%d7%a1%d7%95%d7%a8%d7%95%d7%a7%d7%94/",
        tags: ["סיוע לחולים ומשפחותיהם","באר שבע"],
    },
    {
        id: "1087",
        name: "לב חבד חסד ומרפא הדסה",
        category: "medical",
        city: "ירושלים",
        neighborhood: "הדסה",
        phone: "054-770-9651",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "ישראל נפתלין",
        link: "https://levchabad.org.il/branche/%d7%94%d7%93%d7%a1%d7%94/",
        tags: ["סיוע לחולים ומשפחותיהם","ירושלים"],
    },
    {
        id: "1088",
        name: "לב חבד חסד ומרפא זיו",
        category: "medical",
        city: "צפת",
        neighborhood: "זיו",
        phone: "058-770-6472",
        description: "סיוע לחולים ומשפחותיהם",
        link: "https://levchabad.org.il/branche/%d7%96%d7%99%d7%95/",
        tags: ["סיוע לחולים ומשפחותיהם","צפת"],
    },
    {
        id: "1089",
        name: "לב חבד חסד ומרפא חדרה",
        category: "medical",
        city: "חדרה",
        neighborhood: "חדרה",
        phone: "058-770-5788",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "שניאור ולידור מעטוף",
        link: "https://levchabad.org.il/branche/%d7%97%d7%93%d7%a8%d7%94/",
        tags: ["סיוע לחולים ומשפחותיהם","חדרה"],
    },
    {
        id: "1090",
        name: "לב חבד חסד ומרפא חולון",
        category: "medical",
        city: "חולון",
        neighborhood: "חולון",
        phone: "058-627-7930",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "שמחה ושטערני לנדאו",
        link: "https://levchabad.org.il/branche/%d7%95%d7%95%d7%9c%d7%a4%d7%a1%d7%95%d7%9f/",
        tags: ["סיוע לחולים ומשפחותיהם","חולון"],
    },
    {
        id: "1091",
        name: "לב חבד חסד ומרפא כפר סבא",
        category: "medical",
        city: "כפר סבא",
        phone: "09-7400-414",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "מענדי ומושקי ליפקין",
        link: "https://levchabad.org.il/branche/%d7%9b%d7%a4%d7%a8-%d7%a1%d7%91%d7%90/",
        tags: ["סיוע לחולים ומשפחותיהם","כפר סבא"],
    },
    {
        id: "1092",
        name: "לב חבד חסד ומרפא כרמל- חיפה",
        category: "medical",
        city: "חיפה",
        neighborhood: "כרמל",
        phone: "054-268-1549",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "שלום ומושקא בוקיעט",
        link: "https://levchabad.org.il/branche/%d7%9b%d7%a8%d7%9e%d7%9c/",
        tags: ["סיוע לחולים ומשפחותיהם","חיפה"],
    },
    {
        id: "1093",
        name: "לב חבד חסד ומרפא רחובות",
        category: "medical",
        city: "רחובות",
        phone: "054-329-5771",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "עידן ולילך מקאניק",
        link: "https://levchabad.org.il/branche/%d7%a7%d7%a4%d7%9c%d7%9f-%d7%a8%d7%97%d7%95%d7%91%d7%95%d7%aa/",
        tags: ["סיוע לחולים ומשפחותיהם","רחובות"],
    },
    {
        id: "1094",
        name: "לב חבד חסד ומרפא רמב\"ם",
        category: "medical",
        city: "חיפה",
        neighborhood: "רמבם",
        phone: "053-522-4770",
        description: "סיוע לחולים ומשפחותיהם",
        link: "https://levchabad.org.il/branche/rambam/",
        tags: ["סיוע לחולים ומשפחותיהם","חיפה"],
    },
    {
        id: "1095",
        name: "לב חבד חסד ומרפא שיבא",
        category: "medical",
        city: "תל השומר",
        neighborhood: "שיבא",
        phone: "050-400-6011",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "לוי ואסתי גופין",
        link: "https://levchabad.org.il/branche/%d7%a9%d7%99%d7%91%d7%90_%d7%aa%d7%9c_%d7%94%d7%a9%d7%95%d7%9e%d7%a8_%d7%a8%d7%9e%d7%aa_%d7%92%d7%9f/",
        tags: ["סיוע לחולים ומשפחותיהם","תל השומר"],
    },
    {
        id: "1096",
        name: "לב חבד חסד ומרפא שערי צדק",
        category: "medical",
        city: "ירושלים",
        neighborhood: "שערי צדק",
        phone: "054-797-7007",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "יוני ורחלי שניאורסון",
        link: "https://levchabad.org.il/branche/%d7%a9%d7%a2%d7%a8%d7%99-%d7%a6%d7%93%d7%a7/",
        tags: ["סיוע לחולים ומשפחותיהם","ירושלים"],
    },
    {
        id: "1097",
        name: "לב חבד חסד ומרפא תל אביב",
        category: "medical",
        city: "תל אביב",
        neighborhood: "תל אביב",
        phone: "050-877-7240",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "טל ומושקי גומברג",
        link: "https://levchabad.org.il/branche/%d7%aa%d7%9c_%d7%90%d7%91%d7%99%d7%91/",
        tags: ["סיוע לחולים ומשפחותיהם","תל אביב"],
    },
    {
        id: "1098",
        name: "לב חבד חסד ומרפא תל אביב צפון",
        category: "medical",
        city: "תל אביב",
        neighborhood: "צפון תל אביב",
        phone: "050-877-7240",
        description: "סיוע לחולים ומשפחותיהם",
        contact: "מנחם ופסי ברוד",
        link: "https://levchabad.org.il/branche/%d7%90%d7%a1%d7%95%d7%aa%d7%90_%d7%aa%d7%9c_%d7%90%d7%91%d7%99%d7%91/",
        tags: ["סיוע לחולים ומשפחותיהם","תל אביב"],
    },
    {
        id: "1099",
        name: "גמח רפואה ושלום",
        category: "medical",
        city: "מרכז",
        neighborhood: "בני ברק?",
        phone: "072-3982355",
        description: "יעוץ רפואי ברפואה טבעית מתקדמת",
        tags: ["יעוץ רפואי ברפואה טבעית מתקדמת","מרכז"],
    },
    {
        id: "1100",
        name: "גמח עיצוב הזמנות",
        category: "initiatives",
        city: "?",
        neighborhood: "?",
        description: "עיצוב הזמנות במחיר סמלי",
        tags: ["עיצוב הזמנות במחיר סמלי","?"],
    },
    {
        id: "1101",
        name: "גמח מזודה לחופה",
        category: "wedding",
        city: "ירושלים",
        neighborhood: "ירושלים",
        phone: "054-8488645",
        description: "מזוודה לחופה הכוללת פמוטים ויין ועוד ציוד",
        tags: ["מזוודה לחופה הכוללת פמוטים ויין ועוד ציוד","ירושלים"],
    },
    {
        id: "1102",
        name: "גמח הישועות",
        category: "baby",
        city: "צפון",
        description: "ביגוד, הנעלה, טקסטיל,ציוד לתינוקות וכו",
        tags: ["ביגוד","הנעלה","טקסטיל","ציוד לתינוקות וכו","צפון"],
    },
    {
        id: "1103",
        name: "גמח טנס לידה קלה",
        category: "medical",
        city: "מרכז",
        neighborhood: "שלמה בן יוסף 4, בני ברק",
        description: "מכשיר טנס דגםELLE TENS + כדור פיזיו מצרים ללידה קלה",
        tags: ["מכשיר טנס דגםELLE TENS + כדור פיזיו מצרים ללידה קלה","מרכז"],
    },
    {
        id: "1104",
        name: "קבוצת מתנדבים שמחת אחים",
        category: "medical",
        city: "מרכז",
        description: "משמחים חולים באשפוז ובבית, שמירה על חולים, הכוונה וזירוז הליכים רפואים",
        tags: ["משמחים חולים באשפוז ובבית","שמירה על חולים","הכוונה וזירוז הליכים רפואים","מרכז"],
    },
    {
        id: "1105",
        name: "גמח אחותי כלה",
        category: "wedding",
        city: "מרכז",
        neighborhood: "פתח תקווה",
        phone: "058-786-7426",
        description: "אביזרים לריקודים",
        contact: "hatuna.org@gmail.com",
        link: "https://hatuna.org",
        tags: ["אביזרים לריקודים","מרכז"],
    },
    {
        id: "1106",
        name: "גמח שידוכים",
        category: "judaism",
        city: "אחר",
        description: "מיזם שידוכים חינמי",
        tags: ["מיזם שידוכים חינמי","אחר"],
    },
    {
        id: "1107",
        name: "גמח כיסויים לכסאות",
        category: "furniture",
        city: "כיסויים לכסאות כתר - לשמחות",
        description: "כיסויים לכסאות כתר - לשמחות",
        notes: "בצבע שחור עם סרט זהב. 35 יחידות",
        tags: ["כיסויים לכסאות כתר - לשמחות"],
    },
    {
        id: "1108",
        name: "גמח מרכזי שולחן",
        category: "furniture",
        city: "ירושלים",
        description: "לאירועים ושמחות",
        tags: ["לאירועים ושמחות","ירושלים"],
    },
];
